### ISSUE TITLE
Bug in Scheduler? What format for 

### ISSUE THREAD

**Issue by poornerd** [JakubStas/foosie#29]
Hi,

I am using this parameter: 
`foosie.schedule-before=12
`

But after awhile I am getting errors like this (and can't enter any command without the error "1. Provided time must be in the future but still today!" except /iamin

I think I probably have a problem with this parameter since the errors say something about scheduling, and I also never see the games expire or cancelled.

**Am I using the parameter correctly?**

```
[2017-01-23 14:34:41.621] boot - 3709 ERROR [pool-1-thread-1] --- TaskUtils$LoggingErrorHandler: Unexpected error occurred in scheduled task.
javax.validation.ConstraintViolationException
	at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:144)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at com.jakubstas.foosie.service.model.GamesCache$$EnhancerBySpringCGLIB$$5da5b4aa.findByHostName(<generated>)
	at com.jakubstas.foosie.service.GameScheduler.kickOffUpcomingGames(GameScheduler.java:41)
	at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2017-01-23 14:35:41.622] boot - 3709 ERROR [pool-1-thread-1] --- TaskUtils$LoggingErrorHandler: Unexpected error occurred in scheduled task.
javax.validation.ConstraintViolationException
	at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:144)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at com.jakubstas.foosie.service.model.GamesCache$$EnhancerBySpringCGLIB$$5da5b4aa.findByHostName(<generated>)
	at com.jakubstas.foosie.service.GameScheduler.kickOffUpcomingGames(GameScheduler.java:41)
	at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2017-01-23 14:35:42.638] boot - 3709  INFO [http-nio-8080-exec-4] --- SlackService: Posting quick reply to: https://hooks.slack.com/commands/T3TUFE8UR/131046101299/lhY83WZO8GtsL0gZdYKVBCl0
[2017-01-23 14:35:42.638] boot - 3709  INFO [http-nio-8080-exec-4] --- SlackService: URI = https://hooks.slack.com/commands/T3TUFE8UR/131046101299/lhY83WZO8GtsL0gZdYKVBCl0
[2017-01-23 14:35:42.638] boot - 3709  INFO [http-nio-8080-exec-4] --- SlackService: Message = Your command has failed validation! Please review following issues:

1. Provided time must be in the future but still today!
```

**Comment by JakubStas** [comment]
Hi Brian,

unfortunately I didn't have a chance to test this as much as I would like so it is possible that there are bugs in the code. I will look into it when I have a spare moment and let you know.

**Comment by JakubStas** [comment]
I won't be able to look into this for at least a month.
